---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 26/04/2022 23:21
---
currentCallback = nil
exports("use", function(title,cb)
    useKeyboard(title,cb);
end)

function useKeyboard(title,cb)
    SetTimeout(200,function()
        SetNuiFocus(true,true);
        currentCallback = cb;
        SendNUIMessage({type="showKeyboard",title=title and title or ""});
    end)
end

RegisterCommand('keybo', function()
    useKeyboard('test', 10)
end)

RegisterNUICallback("send",function(data)
    SetNuiFocus(false,false);
    if currentCallback then
        currentCallback(data.text);
        currentCallback = nil;
    end
end)

RegisterNUICallback("cancel",function(data)
    SetNuiFocus(false,false);
    TriggerEvent("kbi:cancel");
end)